# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--skip, "path/to/infra/migrations"]
        entry: isort --diff --check src
        pass_filenames: false
        language_version: python3.10
        always_run: true

-   repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
    - id: black
      name: black
      args: [--exclude, "path/to/infra/migrations"]
      entry: black --diff --check --color src
      pass_filenames: false
      language_version: python3.10
      always_run: true

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        entry: flake8 src
        pass_filenames: false
        language_version: python3.10
        always_run: true


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        args: [--implicit-optional]
        entry: mypy src
        pass_filenames: false
        language_version: python3.10
        always_run: true
        additional_dependencies: [types-requests==2.31.0.9]
