#services:
#  api:
#    build: .
#    container_name: aa-Vector-DBs-application
#    volumes:
#      - ./src:/usr/aa-Vector-DBs/src

version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
