# we use pyproject.toml to configure our project and dependencies
# https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html

[tool.black]
exclude = '(\.git|\.mypy_cache|\.venv)'
include = '\.pyi?$'
line-length = 132
target-version = ['py310']

[tool.mypy]
python_version = "3.10"
no_implicit_optional = false
#explicit_package_bases = true
ignore_missing_imports = true
namespace_packages = true
follow_imports = "skip" # used for https://github.com/python/mypy/issues/13627 since we cant update mypy
