name: Setup Outputs
description: Setup version and commit message outputs

outputs:
  commit-message:
    description: The commit message
    value: ${{ steps.get-commit-message.outputs.message }}
  semver:
    description: The semantic version
    value: ${{ steps.versioning.outputs.semver }}
  rich-version:
    description: The rich version (for docker image tags)
    value: ${{ steps.versioning.outputs.image-tag }}

runs:
  using: 'composite'
  steps:
    - name: Get commit message
      id: get-commit-message
      shell: bash
      run: |
        MESSAGE=$(git show -s --format=%s)
        echo "Commit message: ${MESSAGE}"
        echo "message=${MESSAGE}" >> $GITHUB_OUTPUT
