name: CI Workflow
run-name: ${{ github.repository }} Main Workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


jobs:
  prepare-outputs:
    name: Prepare outputs
    runs-on: ubuntu-latest

    outputs:
      commit-message: ${{ steps.outputs-setup.outputs.commit-message }}
      semver: ${{ steps.outputs-setup.outputs.semver }}
      rich-version: ${{ steps.outputs-setup.outputs.rich-version }}

    steps:
      - name: Checkout head commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Set outputs
        id: outputs-setup
        uses: ./.github/actions/outputs-setup

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: prepare-outputs
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up
        uses: ./.github/actions/python-setup

      - name: Check
        id: check
        run: |
          make check

      - name: Run unit tests
        run: |
          make unit
